### ISSUE TITLE
Error in step1

### ISSUE THREAD

**Issue by baravalle** [brian-cleary/LatentStrainAnalysis#17]
Hi,
I'm trying step 1: `bash HashCounting.sh 6 33 22`

but I get some problems with the parallel call. The option --no-notice doesn't seem to be available in my version - so I have removed it.

This is what I get, with bash -x (the CreateHash code seems to be working, so I have commented the lines after the first execution):

`bash -x HashCounting.sh 6 33 22
\+ '[' 3 -ne 3 ']'
\+ numThreads=6
\+ kmerLen=33
\+ export hashSize=22
\+ hashSize=22
\+ mkdir Logs
mkdir: cannot create directory `Logs': File exists
\+\+ grep '^-'
\+\+ wc -l
\+\+ ls -l original_reads/SRR492065.10kReads.plusSpike.fastq original_reads/SRR492066.10kReads.plusSpike.fastq original_reads/SRR492182.10kReads.plusSpike.fastq                                                 original_reads/SRR492183.10kReads.plusSpike.fastq original_reads/SRR492184.10kReads.plusSpike.fastq original_reads/SRR492185.10kReads.plusSpike.fastq original_                                                reads/SRR492186.10kReads.plusSpike.fastq original_reads/SRR492187.10kReads.plusSpike.fastq original_reads/SRR492188.10kReads.plusSpike.fastq original_reads/SRR                                                492189.10kReads.plusSpike.fastq original_reads/SRR492190.10kReads.plusSpike.fastq original_reads/SRR492191.10kReads.plusSpike.fastq original_reads/SRR492192.10                                                kReads.plusSpike.fastq original_reads/SRR492193.10kReads.plusSpike.fastq original_reads/SRR492194.10kReads.plusSpike.fastq original_reads/SRR492195.10kReads.pl                                                usSpike.fastq original_reads/SRR492196.10kReads.plusSpike.fastq original_reads/SRR492197.10kReads.plusSpike.fastq
\+ numInputFiles=18
\+\+ seq 1 18
\+ parallel -j 6 --halt-on-error 2 'echo $(date) hashing reads in file {}; \
python LSA/hash_fastq_reads.py -r {} -i original_reads/ -o hashed_reads/ >> Logs/HashReads.log 2>&1' ::: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
parallel: Warning: YOU ARE USING --tollef. IF THINGS ARE ACTING WEIRD USE --gnu.
parallel: Warning: --tollef is obsolete and will be retired 20140222.
parallel: Warning: See: http://lists.gnu.org/archive/html/parallel/2013-02/msg00018.html
Thu Feb 4 23:55:26 GMT 2016 hashing reads in file {}
/bin/bash: :::: command not found
/bin/bash: 1: command not found
/bin/bash: 2: command not found
parallel: This job failed:
/bin/bash -c :::
/bin/bash: 3: command not found
\+ '[' 127 -ne 0 ']'
\+ echo 'printing end of last log file...'
printing end of last log file...
\+ tail Logs/HashReads.log
/bin/bash: 4: command not found
    fr = int(arg) - 1
ValueError: invalid literal for int() with base 10: '{}'
Traceback (most recent call last):
  File "LSA/hash_fastq_reads.py", line 54, in <module>
    fr = int(arg) - 1
ValueError: invalid literal for int() with base 10: '{}'
Traceback (most recent call last):
  File "LSA/hash_fastq_reads.py", line 54, in <module>
    fr = int(arg) - 1
ValueError: invalid literal for int() with base 10: '{}'
\+ exit 1`

Any ideas of what this could be?

      Andres

**Comment by baravalle** [comment]
Hi all,
the problem was in the library versions - with more up to date libraries I managed to go through the test data.

     Andres
