### ISSUE TITLE
Problem with MergeHash 

### ISSUE THREAD

**Issue by davidmartinad200** [brian-cleary/LatentStrainAnalysis#18]
Hi when running the MergeHash function i have this problem....

python LSFScripts/create_jobs.py -j MergeHash -i ./
**MergeHash array size will be 0**

The steps before went almost well except for the Split function. It seems it is looking for a single file. I have submitted a paired-end expriment , both files names sample_id.MOCK.fastq.1 sample_id.MOCK.fastq.2  but i don´t have singletons.

Any idea ???

Traceback (most recent call last):
  File "LSFScripts/merge_and_split_pair_files.py", line 80, in <module>
    rw = split_singletons(sing,out)
  File "LSFScripts/merge_and_split_pair_files.py", line 33, in split_singletons
    f1 = open(sing_path)
IOError: [Errno 2] No such file or directory: 'MOCK/sample_i
d.MOCK.single.fastq.1'
Traceback (most recent call last):
  File "LSFScripts/merge_and_split_pair_files.py", line 80, in <module>
    rw = split_singletons(sing,out)
  File "LSFScripts/merge_and_split_pair_files.py", line 33, in split_singletons
    f1 = open(sing_path)
IOError: [Errno 2] No such file or directory: 'MOCK/sample_i
d.MOCK.single.fastq.2'

**Comment by jonoave** [comment]
I'm facing a similar issue. Is there an option to disable the flag for singletons? 
Is any of the authors still responding to this issue?
